### ISSUE TITLE
how to add gamma profile and flip point to the chart

### ISSUE THREAD

**Issue by rozigiusz** [Smayxor/stock#2]
For first, thank you very much for providing with this script, it is amazing, but i have problem to implement delta and gamma profile to the script, can you tell me how i can do that ?

Thanks in advance

**Comment by Smayxor** [comment]
oh hello.  sorry i never looked at the messages here before.   i have been doing some pretty major updates since december.   i may try to add the Zero Gamma Flip Point in the future,  i have to try and understand how to calculate it still.  I just got done adding more chart types,  you can now display changes GEX/DEX/OI from the last time u printed a chart.  It also now logs IV, and can make a monthly IV chart.
Yes the Zero Gamma Point is on my things to do list, I have code samples that use Pandas/Numpy to do it, but I am using an OOPS aproach so I have to reverse engineer

**Comment by Smayxor** [comment]
Zero Gamma, aka Gamma Flip Point has been added.   I'm still doing some evaluations on the code, so im showing 2 values right now
You can always just use my discord,  thats where I keep the bot running.  https://discord.gg/SPAWhtBSMY
